version: '3.8'

services:
  web:
    build: .
    container_name: aws-practice-exam
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge